/** @file
 *
 *  Copyright (c) 2024, Mario Bălănică <mariobalanica02@gmail.com>
 *
 *  SPDX-License-Identifier: BSD-2-Clause-Patent
 *
 **/

#ifndef __BCM2712_PCIE_H__
#define __BCM2712_PCIE_H__

#define BRCM_PCIE_CAP_REGS                                 0x00ac
#define PCIE_LINK_CAPABILITIES                             0xc
#define  PCIE_LINK_CAPABILITIES_SUPPORTED_LINK_SPEED_MASK  0xf
#define PCIE_LINK_STATUS                                   0x12
#define  PCIE_LINK_STATUS_LINK_SPEED_MASK                  0xf
#define  PCIE_LINK_STATUS_LINK_WIDTH_SHIFT                 4
#define  PCIE_LINK_STATUS_LINK_WIDTH_MASK                  (0x3f << 4)
#define PCIE_LINK_CONTROL_2                                0x30
#define  PCIE_LINK_CONTROL_2_TARGET_LINK_SPEED_MASK        0xf

#define PCIE_RC_CFG_VENDOR_VENDOR_SPECIFIC_REG1                          0x0188
#define  PCIE_RC_CFG_VENDOR_VENDOR_SPECIFIC_REG1_ENDIAN_MODE_BAR2_SHIFT  2
#define  PCIE_RC_CFG_VENDOR_VENDOR_SPECIFIC_REG1_ENDIAN_MODE_BAR2_MASK   (0x3 << 2)
#define  PCIE_RC_CFG_VENDOR_SPCIFIC_REG1_LITTLE_ENDIAN                   0x0

#define PCIE_RC_CFG_PRIV1_ID_VAL3                   0x043c
#define  PCIE_RC_CFG_PRIV1_ID_VAL3_CLASS_CODE_MASK  0xffffff

#define PCIE_RC_CFG_PRIV1_LINK_CAPABILITY                      0x04dc
#define  PCIE_RC_CFG_PRIV1_LINK_CAPABILITY_ASPM_SUPPORT_SHIFT  10
#define  PCIE_RC_CFG_PRIV1_LINK_CAPABILITY_ASPM_SUPPORT_MASK   (0x3 << 10)
#define  PCIE_LINK_STATE_L0S                                   BIT0
#define  PCIE_LINK_STATE_L1                                    BIT1
#define  PCIE_LINK_STATE_CLKPM                                 BIT2
#define  PCIE_LINK_STATE_L1_1                                  BIT3
#define  PCIE_LINK_STATE_L1_2                                  BIT4
#define  PCIE_LINK_STATE_L1_1_PCIPM                            BIT5
#define  PCIE_LINK_STATE_L1_2_PCIPM                            BIT6

#define PCIE_RC_TL_VDM_CTL0                         0x0a20
#define  PCIE_RC_TL_VDM_CTL0_VDM_ENABLED_MASK       0x10000
#define  PCIE_RC_TL_VDM_CTL0_VDM_IGNORETAG_MASK     0x20000
#define  PCIE_RC_TL_VDM_CTL0_VDM_IGNOREVNDRID_MASK  0x40000

#define PCIE_RC_TL_VDM_CTL1                    0x0a0c
#define  PCIE_RC_TL_VDM_CTL1_VDM_VNDRID0_MASK  0x0000ffff
#define  PCIE_RC_TL_VDM_CTL1_VDM_VNDRID1_MASK  0xffff0000

#define PCIE_RC_DL_MDIO_ADDR          0x1100
#define  PCIE_RC_DL_MDIO_CMD_SHIFT    20
#define  PCIE_RC_DL_MDIO_CMD_MASK     (0xfff << 20)
#define  PCIE_RC_DL_MDIO_CMD_READ     0x1
#define  PCIE_RC_DL_MDIO_CMD_WRITE    0x0
#define  PCIE_RC_DL_MDIO_PORT_SHIFT   16
#define  PCIE_RC_DL_MDIO_PORT_MASK    (0xf << 16)
#define  PCIE_RC_DL_MDIO_REGAD_SHIFT  0
#define  PCIE_RC_DL_MDIO_REGAD_MASK   (0xffff << 0)

#define PCIE_RC_DL_MDIO_PACKET(_Port, _Reg, _Cmd) \
  (_Port << PCIE_RC_DL_MDIO_PORT_SHIFT | \
  _Reg << PCIE_RC_DL_MDIO_REGAD_SHIFT | \
  _Cmd << PCIE_RC_DL_MDIO_CMD_SHIFT)

#define PCIE_RC_DL_MDIO_WR_DATA          0x1104
#define PCIE_RC_DL_MDIO_RD_DATA          0x1108
#define  PCIE_RC_DL_MDIO_DATA_SHIFT      0
#define  PCIE_RC_DL_MDIO_DATA_MASK       (0x7fffffff << 0)
#define  PCIE_RC_DL_MDIO_DATA_DONE_MASK  0x80000000

#define PCIE_RC_PL_PHY_CTL_15                      0x184c
#define  PCIE_RC_PL_PHY_CTL_15_PM_CLK_PERIOD_MASK  0xff

#define PCIE_MISC_MISC_CTRL                          0x4008
#define  PCIE_MISC_MISC_CTRL_PCIE_RCB_64B_MODE_MASK  0x80
#define  PCIE_MISC_MISC_CTRL_PCIE_RCB_MPS_MODE_MASK  0x400
#define  PCIE_MISC_MISC_CTRL_SCB_ACCESS_EN_MASK      0x1000
#define  PCIE_MISC_MISC_CTRL_CFG_READ_UR_MODE_MASK   0x2000
#define  PCIE_MISC_MISC_CTRL_MAX_BURST_SIZE_SHIFT    20
#define  PCIE_MISC_MISC_CTRL_MAX_BURST_SIZE_MASK     (0x3 << 20)
#define  PCIE_MISC_MISC_CTRL_MAX_BURST_SIZE_128      1
#define  PCIE_MISC_MISC_CTRL_MAX_BURST_SIZE_256      2
#define  PCIE_MISC_MISC_CTRL_MAX_BURST_SIZE_512      3
#define  PCIE_MISC_MISC_CTRL_SCB0_SIZE_SHIFT         27
#define  PCIE_MISC_MISC_CTRL_SCB0_SIZE_MASK          (0x1f << 27)
#define  PCIE_MISC_MISC_CTRL_SCB1_SIZE_SHIFT         22
#define  PCIE_MISC_MISC_CTRL_SCB1_SIZE_MASK          (0x1f << 22)
#define  PCIE_MISC_MISC_CTRL_SCB2_SIZE_SHIFT         0
#define  PCIE_MISC_MISC_CTRL_SCB2_SIZE_MASK          (0x1f << 0)

#define PCIE_MISC_CPU_2_PCIE_MEM_WIN0_LO  0x400c
#define PCIE_MISC_CPU_2_PCIE_MEM_WIN0_HI  0x4010

#define PCIE_MEM_WIN_LO(_Idx)  PCIE_MISC_CPU_2_PCIE_MEM_WIN0_LO + ((_Idx) * 8)
#define PCIE_MEM_WIN_HI(_Idx)  PCIE_MISC_CPU_2_PCIE_MEM_WIN0_HI + ((_Idx) * 8)

#define PCIE_MISC_RC_BAR1_CONFIG_LO  0x402c
#define PCIE_MISC_RC_BAR1_CONFIG_HI  0x4030

#define PCIE_MISC_RC_BAR2_CONFIG_LO  0x4034
#define PCIE_MISC_RC_BAR2_CONFIG_HI  0x4038

#define PCIE_MISC_RC_BAR3_CONFIG_LO  0x403c
#define PCIE_MISC_RC_BAR3_CONFIG_HI  0x4040

#define PCIE_MISC_RC_CONFIG_RETRY_TIMEOUT  0x405c

#define PCIE_MISC_PCIE_CTRL                         0x4064
#define  PCIE_MISC_PCIE_CTRL_PCIE_L23_REQUEST_MASK  0x1
#define  PCIE_MISC_PCIE_CTRL_PCIE_PERSTB_MASK       0x4

#define PCIE_MISC_PCIE_STATUS                         0x4068
#define  PCIE_MISC_PCIE_STATUS_PCIE_DL_ACTIVE_MASK    0x20
#define  PCIE_MISC_PCIE_STATUS_PCIE_PHYLINKUP_MASK    0x10
#define  PCIE_MISC_PCIE_STATUS_PCIE_LINK_IN_L23_MASK  0x40

#define PCIE_MISC_CPU_2_PCIE_MEM_WIN0_BASE_LIMIT              0x4070
#define  PCIE_MISC_CPU_2_PCIE_MEM_WIN_BASE_LIMIT_MASK_BITS    12
#define  PCIE_MISC_CPU_2_PCIE_MEM_WIN_BASE_LIMIT_LIMIT_SHIFT  20
#define  PCIE_MISC_CPU_2_PCIE_MEM_WIN_BASE_LIMIT_LIMIT_MASK   (0xfff << 20)
#define  PCIE_MISC_CPU_2_PCIE_MEM_WIN_BASE_LIMIT_BASE_SHIFT   4
#define  PCIE_MISC_CPU_2_PCIE_MEM_WIN_BASE_LIMIT_BASE_MASK    (0xfff << 4)

#define PCIE_MISC_CPU_2_PCIE_MEM_WIN0_BASE_HI              0x4080
#define  PCIE_MISC_CPU_2_PCIE_MEM_WIN_BASE_HI_BASE_MASK    0xff
#define PCIE_MISC_CPU_2_PCIE_MEM_WIN0_LIMIT_HI             0x4084
#define  PCIE_MISC_CPU_2_PCIE_MEM_WIN_LIMIT_HI_LIMIT_MASK  0xff

#define PCIE_MEM_WIN_BASE_LIMIT(_Idx)  (PCIE_MISC_CPU_2_PCIE_MEM_WIN0_BASE_LIMIT + ((_Idx) * 4))
#define PCIE_MEM_WIN_BASE_HI(_Idx)     (PCIE_MISC_CPU_2_PCIE_MEM_WIN0_BASE_HI + ((_Idx) * 8))
#define PCIE_MEM_WIN_LIMIT_HI(_Idx)    (PCIE_MISC_CPU_2_PCIE_MEM_WIN0_LIMIT_HI + ((_Idx) * 8))

#define PCIE_MISC_HARD_PCIE_HARD_DEBUG                            0x4304
#define  PCIE_MISC_HARD_PCIE_HARD_DEBUG_CLKREQ_DEBUG_ENABLE_MASK  0x2
#define  PCIE_MISC_HARD_PCIE_HARD_DEBUG_PERST_ASSERT_MASK         0x8
#define  PCIE_MISC_HARD_PCIE_HARD_DEBUG_SERDES_IDDQ_MASK          0x08000000
#define  PCIE_BMIPS_MISC_HARD_PCIE_HARD_DEBUG_SERDES_IDDQ_MASK    0x00800000
#define  PCIE_MISC_HARD_PCIE_HARD_DEBUG_CLKREQ_L1SS_ENABLE_MASK   0x00200000

#define PCIE_MISC_CTRL_1                           0x40A0
#define  PCIE_MISC_CTRL_1_OUTBOUND_TC_MASK         0xf
#define  PCIE_MISC_CTRL_1_OUTBOUND_NO_SNOOP_MASK   BIT3
#define  PCIE_MISC_CTRL_1_OUTBOUND_RO_MASK         BIT4
#define  PCIE_MISC_CTRL_1_EN_VDM_QOS_CONTROL_MASK  BIT5

#define PCIE_MISC_UBUS_CTRL                                   0x40a4
#define  PCIE_MISC_UBUS_CTRL_UBUS_PCIE_REPLY_ERR_DIS_MASK     BIT13
#define  PCIE_MISC_UBUS_CTRL_UBUS_PCIE_REPLY_DECERR_DIS_MASK  BIT19

#define PCIE_MISC_UBUS_TIMEOUT  0x40A8

#define PCIE_MISC_UBUS_BAR1_CONFIG_REMAP_LO  0x40ac
#define PCIE_MISC_UBUS_BAR1_CONFIG_REMAP_HI  0x40b0

#define PCIE_MISC_UBUS_BAR2_CONFIG_REMAP_LO  0x40b4
#define PCIE_MISC_UBUS_BAR2_CONFIG_REMAP_HI  0x40b8

#define PCIE_MISC_RC_BAR4_CONFIG_LO            0x40d4
#define PCIE_MISC_RC_BAR4_CONFIG_HI            0x40d8
#define  PCIE_MISC_RC_BAR_CONFIG_LO_SIZE_MASK  0x1f

#define PCIE_IB_WIN_LO(_Idx) \
  ((_Idx == 0) ? PCIE_MISC_RC_BAR2_CONFIG_LO \
               : PCIE_MISC_RC_BAR4_CONFIG_LO + ((_Idx - 1) * 8))

#define PCIE_IB_WIN_HI(_Idx) \
  ((_Idx == 0) ? PCIE_MISC_RC_BAR2_CONFIG_HI \
               : PCIE_MISC_RC_BAR4_CONFIG_HI + ((_Idx - 1) * 8))

#define PCIE_MISC_UBUS_BAR_CONFIG_REMAP_ENABLE   BIT0
#define PCIE_MISC_UBUS_BAR_CONFIG_REMAP_LO_MASK  0xfffff000
#define PCIE_MISC_UBUS_BAR_CONFIG_REMAP_HI_MASK  0xff
#define PCIE_MISC_UBUS_BAR4_CONFIG_REMAP_LO      0x410c
#define PCIE_MISC_UBUS_BAR4_CONFIG_REMAP_HI      0x4110

#define PCIE_IB_WIN_REMAP_LO(_Idx)  \
  ((_Idx == 0) ? PCIE_MISC_UBUS_BAR2_CONFIG_REMAP_LO \
               : PCIE_MISC_UBUS_BAR4_CONFIG_REMAP_LO + ((_Idx - 1) * 8))

#define PCIE_IB_WIN_REMAP_HI(_Idx) \
  ((_Idx == 0) ? PCIE_MISC_UBUS_BAR2_CONFIG_REMAP_HI \
               : PCIE_MISC_UBUS_BAR4_CONFIG_REMAP_HI + ((_Idx - 1) * 8))

#define PCIE_MISC_VDM_PRIORITY_TO_QOS_MAP_HI  0x4164
#define PCIE_MISC_VDM_PRIORITY_TO_QOS_MAP_LO  0x4168

#define PCIE_MISC_AXI_INTF_CTRL          0x416C
#define  AXI_REQFIFO_EN_QOS_PROPAGATION  BIT7

#define PCIE_MISC_AXI_READ_ERROR_DATA  0x4170

#define PCIE_INTR2_CPU_BASE      0x4400
#define PCIE_INTR2_CPU_MASK_SET  0x10
#define PCIE_INTR2_CPU_MASK_CLR  0x14

#define PCIE_EXT_CFG_DATA   0x8000
#define PCIE_EXT_CFG_INDEX  0x9000

#define MDIO_PHY_SET_ADDR_OFFSET  0x1f

#define PCIE_NUM_INBOUND_WINDOWS   8
#define PCIE_NUM_OUTBOUND_WINDOWS  4

#define PCI_INVALID_ADDRESS  0xffffffff

#endif // __BCM2712_PCIE_H__
